"""create core tables

Revision ID: 085a6b5dd0e6
Revises: 
Create Date: 2026-08-15 23:12:52.134055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085a6b5dd0e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('doctors',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('activation_code', sa.String(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctors_activation_code'), 'doctors', ['activation_code'], unique=True)
    op.create_table('patients',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('baseline_risk', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('baseline_computed_at', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('push_subscription', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointments',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'confirmed', 'declined', 'cancelled', name='appointmentstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_doctor_id'), 'availability_slots', ['doctor_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='uq_consent_pair')
    )
    op.create_index(op.f('ix_consent_records_doctor_id'), 'consent_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consent_records_patient_id'), 'consent_records', ['patient_id'], unique=False)
    op.create_table('daily_checkins',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Enum('morning', 'night', name='checkinslot'), nullable=False),
    sa.Column('chest_pain', sa.Integer(), nullable=False),
    sa.Column('breathlessness', sa.Integer(), nullable=False),
    sa.Column('fatigue', sa.Integer(), nullable=False),
    sa.Column('swelling', sa.Integer(), nullable=False),
    sa.Column('dizziness', sa.Integer(), nullable=False),
    sa.Column('medication_taken', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('good', 'fair', 'bad', name='conditionstatus'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Enum('routine', 'elevated', 'emergency', name='urgency'), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('fired_rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'check_date', 'slot', name='uq_checkin_slot')
    )
    op.create_index(op.f('ix_daily_checkins_patient_id'), 'daily_checkins', ['patient_id'], unique=False)
    op.create_table('family_history',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('relation', sa.String(), nullable=False),
    sa.Column('condition', sa.String(), nullable=False),
    sa.Column('age_at_diagnosis', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_family_history_patient_id'), 'family_history', ['patient_id'], unique=False)
    op.create_table('medical_records',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('sex', sa.String(), nullable=False),
    sa.Column('chest_pain_type', sa.Integer(), nullable=False),
    sa.Column('resting_bp', sa.Integer(), nullable=False),
    sa.Column('cholesterol', sa.Integer(), nullable=False),
    sa.Column('fasting_bs_high', sa.Boolean(), nullable=False),
    sa.Column('resting_ecg', sa.Integer(), nullable=False),
    sa.Column('max_heart_rate', sa.Integer(), nullable=False),
    sa.Column('exercise_angina', sa.Boolean(), nullable=False),
    sa.Column('oldpeak', sa.Float(), nullable=False),
    sa.Column('st_slope', sa.Integer(), nullable=False),
    sa.Column('major_vessels', sa.Integer(), nullable=False),
    sa.Column('thalassemia', sa.Integer(), nullable=False),
    sa.Column('medications', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('notification_logs',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('urgency', sa.Enum('routine', 'elevated', 'emergency', name='urgency'), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_patient_id'), 'notification_logs', ['patient_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('consent_record_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_patient_id'), 'audit_logs', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_notification_logs_patient_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('medical_records')
    op.drop_index(op.f('ix_family_history_patient_id'), table_name='family_history')
    op.drop_table('family_history')
    op.drop_index(op.f('ix_daily_checkins_patient_id'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    op.drop_index(op.f('ix_consent_records_patient_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_doctor_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_availability_slots_doctor_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_activation_code'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###