"""baseline schema

Revision ID: 1cef8d9eb252
Revises: 
Create Date: 2026-08-29 22:25:09.480960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cef8d9eb252'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('doctors',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('staff_id', sa.String(), nullable=True),
    sa.Column('activation_code', sa.String(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('qualifications', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('hospital', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_doctors_activation_code'), 'doctors', ['activation_code'], unique=True)
    op.create_index(op.f('ix_doctors_staff_id'), 'doctors', ['staff_id'], unique=True)
    op.create_table('patients',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('baseline_risk', sa.Enum('low', 'medium', 'high', name='risklevel'), nullable=True),
    sa.Column('baseline_score', sa.Float(), nullable=True),
    sa.Column('baseline_computed_at', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('push_subscription', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('appointments',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'cancelled', 'completed', name='appointmentstatus'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_table('availability_slots',
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_slots_doctor_id'), 'availability_slots', ['doctor_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='uq_consent_pair')
    )
    op.create_index(op.f('ix_consent_records_doctor_id'), 'consent_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_consent_records_patient_id'), 'consent_records', ['patient_id'], unique=False)
    op.create_table('daily_checkins',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('check_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.Enum('morning', 'night', name='checkinslot'), nullable=False),
    sa.Column('chest_pain', sa.Boolean(), nullable=False),
    sa.Column('breathlessness', sa.Boolean(), nullable=False),
    sa.Column('breathlessness_trigger', sa.Enum('none', 'stairs', 'walking', 'at_rest', name='breathlessnesstrigger'), nullable=False),
    sa.Column('dizziness', sa.Boolean(), nullable=False),
    sa.Column('fatigue', sa.Boolean(), nullable=False),
    sa.Column('palpitations', sa.Boolean(), nullable=False),
    sa.Column('swelling', sa.Boolean(), nullable=False),
    sa.Column('worse_than_usual', sa.Boolean(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=True),
    sa.Column('diastolic_bp', sa.Integer(), nullable=True),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('medication_taken', sa.Boolean(), nullable=False),
    sa.Column('medication_missed', sa.Boolean(), nullable=False),
    sa.Column('extra_medication', sa.Boolean(), nullable=False),
    sa.Column('diet_note', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('good', 'fair', 'bad', name='conditionstatus'), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('urgency', sa.Enum('routine', 'elevated', 'emergency', name='urgency'), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('fired_rules', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'check_date', 'slot', name='uq_checkin_slot')
    )
    op.create_index(op.f('ix_daily_checkins_patient_id'), 'daily_checkins', ['patient_id'], unique=False)
    op.create_table('family_history',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('heart_disease', sa.Enum('yes', 'no', 'unknown', name='tristate'), nullable=False),
    sa.Column('hypertension', sa.Enum('yes', 'no', 'unknown', name='tristate'), nullable=False),
    sa.Column('diabetes', sa.Enum('yes', 'no', 'unknown', name='tristate'), nullable=False),
    sa.Column('premature_heart_disease', sa.Enum('yes', 'no', 'unknown', name='tristate'), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('lifestyle_history',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('smokes_now', sa.Boolean(), nullable=False),
    sa.Column('smoked_in_past', sa.Boolean(), nullable=False),
    sa.Column('physical_activity', sa.Enum('low', 'moderate', 'high', name='activitylevel'), nullable=False),
    sa.Column('occupation_activity', sa.Enum('sedentary', 'light', 'moderate', 'high', name='occupationactivity'), nullable=False),
    sa.Column('drinks_alcohol', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('medical_records',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('systolic_bp', sa.Integer(), nullable=False),
    sa.Column('diastolic_bp', sa.Integer(), nullable=False),
    sa.Column('hypertension', sa.Boolean(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('ischemic_heart_disease', sa.Boolean(), nullable=False),
    sa.Column('heart_failure', sa.Boolean(), nullable=False),
    sa.Column('heart_attack', sa.Boolean(), nullable=False),
    sa.Column('stroke', sa.Boolean(), nullable=False),
    sa.Column('valve_disease', sa.Enum('yes', 'no', 'unknown', name='tristate'), nullable=False),
    sa.Column('other_cardiovascular_disease', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('medication_history',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('takes_long_term_medication', sa.Boolean(), nullable=False),
    sa.Column('medication_list', sa.String(), nullable=True),
    sa.Column('blood_pressure_medication', sa.Boolean(), nullable=False),
    sa.Column('diabetes_medication', sa.Boolean(), nullable=False),
    sa.Column('heart_medication', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('notification_logs',
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('urgency', sa.Enum('routine', 'elevated', 'emergency', name='urgency'), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_patient_id'), 'notification_logs', ['patient_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_user_id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('consent_record_id', sa.String(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['consent_record_id'], ['consent_records.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_patient_id'), 'audit_logs', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_notification_logs_patient_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_table('medication_history')
    op.drop_table('medical_records')
    op.drop_table('lifestyle_history')
    op.drop_table('family_history')
    op.drop_index(op.f('ix_daily_checkins_patient_id'), table_name='daily_checkins')
    op.drop_table('daily_checkins')
    op.drop_index(op.f('ix_consent_records_patient_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_doctor_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_availability_slots_doctor_id'), table_name='availability_slots')
    op.drop_table('availability_slots')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('patients')
    op.drop_index(op.f('ix_doctors_staff_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_activation_code'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###