"""staff_id, hospital, capacity, demographics

Revision ID: ff2821e01aba
Revises: 085a6b5dd0e6
Create Date: 2026-08-27 10:38:15.353077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff2821e01aba'
down_revision: Union[str, None] = '085a6b5dd0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('cancelled_by', sa.String(), nullable=True))
    op.add_column('availability_slots', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('doctors', sa.Column('staff_id', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('hospital', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('address', sa.String(), nullable=True))
    op.create_index(op.f('ix_doctors_staff_id'), 'doctors', ['staff_id'], unique=True)
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('patients', sa.Column('sex', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'sex')
    op.drop_column('patients', 'date_of_birth')
    op.drop_index(op.f('ix_doctors_staff_id'), table_name='doctors')
    op.drop_column('doctors', 'address')
    op.drop_column('doctors', 'hospital')
    op.drop_column('doctors', 'staff_id')
    op.drop_column('availability_slots', 'capacity')
    op.drop_column('appointments', 'cancelled_by')
    op.drop_column('appointments', 'cancelled_at')
    # ### end Alembic commands ###